### ISSUE TITLE
mouseover exists variable no longer works

### ISSUE THREAD

**Issue by aaron-j-reeves** [mundi4/Debounce#3]
target > mouseover > special conditions > unit > assigned target mouseover > exists

if this is enabled then the entire binding and anything after it will not work. No errors, the ability just never casts,

converting to macro text works as expected:

/cast [@mouseover,harm][@focus] Rebuke

**Comment by aaron-j-reeves** [comment]
actually, just changing it from "when the unit exists" to "when the unit is enemy" fixes it

**Comment by mundi4** [comment]
Did you mouseover a friendly unit? If so, the condition was met, but the spell can't be cast on that target, so nothing happens. 

And if your current `@target` is an enemy and your `@mouseover` is friendly, maybe the spell will be casted on `@target`. This can be a problem.  I'll look into this when I have time.

Also remember:
It takes some time to detect a mouseover change (up to 0.2 sec). Blizzard says, *"-- Deliberately ignoring mouseover and others' target changes because they change so much"*. I should've added a tooltip message regarding this, but I was too lazy.

You can use the following script to remove this delay completely(should run every login):
 `/run SecureStateDriverManager:SetAttribute("updatetime", 0)`
Default value is **0.2**.

Or you can just use a macro `/cast [@mouseover,harm][@focus] Rebuke`.


I think now I shouldn't have added a mouseover condition in the first place.  🤔

**Comment by aaron-j-reeves** [comment]
Hello, ive definitely done all of that. been using debounce since literally the day you uploaded it and something changed in the last few days that made "when the unit exists" stop working, had rebuke setup this way from the beginning and its always worked fantastic. its okay though, changing all of the "exists" to "help" or "harm" worked perfectly.

do not worry about your mouseover implementation, it works amazing! Thank you for all your hard work!

**Comment by mundi4** [comment]
Thanks!
