### ISSUE TITLE
Sort by keybind or spell name

### ISSUE THREAD

**Issue by josiahhalme** [mundi4/Debounce#5]
Hi, love your addon.
Would it be possible to implement sorting by spell name or by keybinding?

**Comment by mundi4** [comment]
Hey, thanks for the feedback!

Sorting by spell name won’t work since the order is the priority of the action, but sorting or grouping by keybind might be a good idea. I’ll look into it when I’ve got time, but it will probably require updating the drag-and-drop code—and I hate that part of the code, so it may take some time!

Let me know if you’ve got any other thoughts!

**Comment by aus10code** [comment]
You could group by modifier (shift, ctrl, alt) or user defined groups (offensive, cc/interrupts, defensive, movement, etc...)

**Comment by mundi4** [comment]
Sorry, I don’t want to mess up the drag-drop code, so I just added a search box. Hope this is ok.
